export const SET_IS_LOADING = 'SET_IS_LOADING'
export const TESTS_LOADING_FAILURE = 'TESTS_LOADING_FAILURE'
export const TESTS_LOADING_SUCCESS = 'TESTS_LOADING_SUCCESS'
export const FETCH_TESTS = 'FETCH_TESTS'